---
title: "Final Project"
author: "Yefu Chen"
date: "2021/5/11"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r prepare, echo=FALSE,message=FALSE, results='hide'}
library(ggplot2)
library(stargazer)
library(corrplot)
library(MASS)

final_data <- read.csv("C:/Users/cheny/OneDrive - The University of Texas at Austin/2021 Spring/UIL 2021 Spring/ECO395M/final/W12 data summary2.csv")


final_data$start_short=final_data$start_short/1000
final_data$pop_total_stop=final_data$pop_total_stop/1000
final_data$pop_income_stop=final_data$pop_income_stop/1000
final_data$hh_total_stop=final_data$hh_total_stop/1000
final_data$hh_income_stop=final_data$hh_income_stop/1000

stargazer(final_data, type='text')

res <- cor(final_data)
res <- round(res, 2)

corrplot(res, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)

ggplot(final_data, aes(x=start_short)) + 
  geom_histogram(aes(y=..count..),  binwidth=1000, colour="black", fill="grey") + 
  geom_vline(aes(xintercept=mean(start_short, na.rm=T)), color="red", linetype="dashed", size=1) 

split = initial_split(final_data, prop = 0.8)
train = training(split)
test = testing(split)



model_po <- glm(log(start_short+1) ~ Gap_Zscore_stop + road + junction +
                       pop_total_stop+pop_income_stop+hh_total_stop+hh_income_stop+
                       LU_index,
                  data = train)
predict_po <- predict(model_po, newdata=test)
rmse.po<-rmse(test$start_short, predict_po)
print(rmse.po)

stargazer(model_po, type='text')

```

```{r GBM, echo=FALSE,message=FALSE, results='hide'}
library(readxl)
library(ggplot2)
library(tidyverse)
library(modelr)
library(rsample)
library(mosaic)
library(caret) 
library(MASS)
library(pROC)
library(caret)
library(Metrics)
library(ROCR)
library(pander)
library(stargazer)
library(xgboost)
library(gbm)
library(vip)

final_data <- read.csv("C:/Users/cheny/OneDrive - The University of Texas at Austin/2021 Spring/UIL 2021 Spring/ECO395M/final/W12 data summary2.csv")


final_data$start_short=final_data$start_short/1000
final_data$pop_total_stop=final_data$pop_total_stop/1000
final_data$pop_income_stop=final_data$pop_income_stop/1000
final_data$hh_total_stop=final_data$hh_total_stop/1000
final_data$hh_income_stop=final_data$hh_income_stop/1000

split = initial_split(final_data, prop = 0.8)
train = training(split)
test = testing(split)

hyper_grid <- expand.grid(
  ntree = c(1000, 5000),
  shrinkage = c(.01, .1),
  interaction.depth = c(2, 5,8),
  n.minobsinnode = c(2, 5),
  bag.fraction = c(0.1,0.2,0.3), 
  optimal_trees = 0,              
  min_RMSE = 0                    
)

for(i in 1:nrow(hyper_grid)) {
  # reproducibility
  set.seed(123)
  # train model
  gbm.tune <- gbm(
    formula = start_short ~ Gap_Zscore_stop + road + junction +
                       pop_total_stop+pop_income_stop+hh_total_stop+hh_income_stop+
                       LU_index,
    distribution = "gaussian",
    data = train,
    n.trees = hyper_grid$ntree[i],
    interaction.depth = hyper_grid$interaction.depth[i],
    shrinkage = hyper_grid$shrinkage[i],
    n.minobsinnode = hyper_grid$n.minobsinnode[i],
    bag.fraction = hyper_grid$bag.fraction[i],
    train.fraction = .75,
    n.cores = NULL, # will use all cores by default
    verbose = FALSE
  )
  
  # add min training error and trees to grid
  hyper_grid$optimal_trees[i] <- which.min(gbm.tune$valid.error)
  hyper_grid$min_RMSE[i] <- sqrt(min(gbm.tune$valid.error))
}

hyper_grid %>% 
  dplyr::arrange(min_RMSE) %>%
  head(3)

gbm.fit.final <- gbm(
  formula = start_short ~ Gap_Zscore_stop + road + junction +
                       pop_total_stop+pop_income_stop+hh_total_stop+hh_income_stop+
                       LU_index,
  distribution = "gaussian",
  data = train,
  n.trees = 268,
  interaction.depth = 8,
  shrinkage = 0.10,
  n.minobsinnode = 5,
  bag.fraction = 0.3,
  train.fraction = 0.75,
  n.cores = NULL, 
  verbose = FALSE)

predict_gb <- predict(gbm.fit.final, newdata=test)
rmse.gb <-rmse(test$start_short, predict_gb)
print(rmse.gb)

predict_gb <- predict(gbm.fit.final, newdata=train)
rmse.gb<-rmse(train$start_short, predict_gb)
print(rmse.gb)

vip::vip(gbm.fit.final)

summary(gbm.fit.final)

plot(gbm.fit.final,i="pop_income_stop") 
plot(gbm.fit.final,i="Gap_Zscore_stop") 
plot(gbm.fit.final,i="road") 
```
